---

# Ensure plugins are installed
- name: download s3 plugin from repository
  get_url:
    url: "https://github.com/Aiven-Open/tiered-storage-for-apache-kafka/releases/download/v{{ kafka_tiered_storage_version }}/s3-{{ kafka_tiered_storage_version }}.tgz"
    dest: "/tmp/tiered-storage-for-apache-kafka_s3.tgz"
    owner: kafka
    group: kafka
    mode: '0644'

- name: download core plugin from repository
  get_url:
    url: "https://github.com/Aiven-Open/tiered-storage-for-apache-kafka/releases/download/v{{ kafka_tiered_storage_version }}/core-{{ kafka_tiered_storage_version }}.tgz"
    dest: "/tmp/tiered-storage-for-apache-kafka_core.tgz"
    owner: kafka
    group: kafka
    mode: '0644'

- name: unarchive s3 plugins
  unarchive:
    src: "{{ item }}"
    dest: "{{ kafka_home }}/libs"
    remote_src: yes
  loop:
    - /tmp/tiered-storage-for-apache-kafka_s3.tgz
    - /tmp/tiered-storage-for-apache-kafka_core.tgz

- name: clean up temporary files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /tmp/tiered-storage-for-apache-kafka_s3.tgz
    - /tmp/tiered-storage-for-apache-kafka_core.tgz

- name: fix ownership of kafka libs
  file:
    path: "{{ kafka_home }}/libs"
    owner: kafka
    group: kafka
    mode: '0644'
    recurse: yes

# Cache
- name: ensure cache folder is initialised
  file:
    path: "/etc/mysqld_exporter"
    state: directory
    owner: kafka
    group: kafka
    mode: "0750"